That's 5207R on top of 5106R to highlight the changes needed to bring 5106R up to par.

diff --git a/BlueOnyx/tmp/5106r5207rdiff/base-blueonyx.mod/templates/rpmdefs.tmpl b/BlueOnyx/tmp/5106r5207rdiff/base-blueonyx.mod/templates/rpmdefs.tmpl
--- a/BlueOnyx/tmp/5106r5207rdiff/base-blueonyx.mod/templates/rpmdefs.tmpl
+++ b/BlueOnyx/tmp/5106r5207rdiff/base-blueonyx.mod/templates/rpmdefs.tmpl
@@ -37,15 +37,8 @@ Group: System Environment/BlueOnyx
 Summary: [LABEL] for [VENDOR]-[SERVICE].
 [AUTOFILL]
 [BUILDARCH]
-%if "%fedora" == "1"
-Requires: pwdb >= 0.61.1-9BQ7 nss_db >= 2.2-22BQ3
-%endif
-%if "%centos" == "3"
-Requires: pwdb >= 0.61.1-9BQ8 nss_db >= 2.2-20.4BQ1
-%endif
-%if "%centos" == "4"
-Requires: pwdb >= 0.61.1-9BQ8 nss_db >= 2.2-29BQ1 php-mbstring
-%endif
+
+Requires: php-mbstring
 
 %description [LABEL]
 The [VENDOR]-[SERVICE]-[LABEL] package contains the [LABEL]
@@ -175,22 +168,6 @@ if [ $? = 1 ]; then
   /bin/rpm --import /usr/share/doc/blueonyx-release-5106R/RPM-GPG-KEY-NUSOL-5106R
 fi
 
-
-%if "%fedora" == "1"
-/bin/cp /usr/sausalito/triggers/yum/yum-fc1.conf /etc/yum.conf
-%endif
-%if "%centos" == "3"
-/bin/cp /usr/sausalito/triggers/yum/yum-centos3.conf /etc/yum.conf
-%endif
-%if "%centos" == "4"
-/usr/bin/perl -pi -e 's|gpgcheck=0|gpgcheck=1|g' /etc/yum.repos.d/BlueQuartz-Base.repo
-%endif
-%if "%centos" == "5" 
-#perl -pi -e 's|gpgcheck=0|gpgcheck=1|g' /etc/yum.repos.d/BlueQuartz-Base.repo 
-# Set ServerTokens in httpd.conf to reveal very little info (i.e.: just 'Apache'):
-/usr/bin/perl -pi -e 's|^ServerTokens OS|ServerTokens ProductOnly|g' /etc/httpd/conf/httpd.conf
-%endif 
-
 # pwdb2shadow
 if [ -f /etc/sysconfig/blueonyx ]; then
   . /etc/sysconfig/blueonyx
@@ -207,6 +184,7 @@ fi
 # Fix php.ini:
 if [ -f /etc/php.ini ]; then
     /usr/bin/perl -pi -e 's|^error_reporting  =  E_ALL|error_reporting  =  E_ALL & ~E_NOTICE|g' /etc/php.ini
+    /usr/bin/perl -pi -e 's|^short_open_tag = Off|short_open_tag = On|g' /etc/php.ini
 fi
 
 # Fix /etc/logwatch/conf/ignore.conf if we're running in a VPS:
@@ -217,6 +195,14 @@ if [ -f /proc/user_beancounters ]; then
         echo "ERROR: cannot set security context" >> /etc/logwatch/conf/ignore.conf
         echo "crond.*: System error" >> /etc/logwatch/conf/ignore.conf
     fi
+fi
+
+# Fix Dovecot v2.0 configs:
+if [ -f /etc/dovecot/conf.d/10-auth.conf ]; then
+	perl -pi -e 's|^#disable_plaintext_auth = (.*)|disable_plaintext_auth = no|g' /etc/dovecot/conf.d/10-auth.conf
+fi
+if [ -f /etc/dovecot/conf.d/10-mail.conf ]; then
+	perl -pi -e 's|^#mail_location =(.*)|mail_location = mbox:~/mail/:INBOX=mbox|g' /etc/dovecot/conf.d/10-mail.conf
 fi
 
 <end glue>
@@ -291,6 +277,30 @@ fi
 /usr/sausalito/constructor/base/time/syncTimeZone.pl
 
 # for distributions
+%if "%centos" == "6"
+%triggerin glue -- iptables
+/bin/cp /usr/sausalito/triggers/iptables/iptables-CentOS5.init /etc/init.d/iptables
+%triggerin glue -- initscripts
+/bin/cp /usr/sausalito/triggers/initscripts/ifup-CentOS5 /sbin/ifup
+%triggerin glue -- httpd
+/usr/bin/perl -pi -e 's|^ServerTokens OS|ServerTokens ProductOnly|g' /etc/httpd/conf/httpd.conf
+# Fix /etc/logrotate.conf, because we want to rotate daily and we want to compress the logs:
+/usr/bin/perl -pi -e 's|^# rotate log files weekly|# rotate log files daily|g' /etc/logrotate.conf
+/usr/bin/perl -pi -e 's|^weekly|daily|g' /etc/logrotate.conf
+/usr/bin/perl -pi -e 's|^#compress|compress|g' /etc/logrotate.conf
+/usr/bin/perl -pi -e 's|^# keep 4 weeks worth of backlogs|# keep 366 days worth of backlogs|g' /etc/logrotate.conf
+/usr/bin/perl -pi -e 's|^rotate 4|rotate 366|g' /etc/logrotate.conf
+%triggerin glue -- logrotate
+/usr/bin/perl -pi -e 's|^#compress|compress|g' /etc/logrotate.conf
+# Fix Logwatch's ignore.conf to ignore error message on Proftpd using virtualhost containers for single IP setups:
+if [ -f /etc/logwatch/conf/ignore.conf ]; then
+  grep '^warning: "ProFTPD" address/port' /etc/logwatch/conf/ignore.conf > /dev/null 2>&1
+  if [ $? = 1 ]; then
+    echo 'warning: "ProFTPD" address/port' >> /etc/logwatch/conf/ignore.conf
+  fi
+fi
+%endif
+
 %if "%centos" == "5"
 %triggerin glue -- iptables
 /bin/cp /usr/sausalito/triggers/iptables/iptables-CentOS5.init /etc/init.d/iptables
@@ -324,12 +334,29 @@ fi
 /bin/cp /usr/sausalito/triggers/initscripts/ifup-CentOS4 /sbin/ifup
 %endif
 
+%if "%centos" == "4"
 %triggerin glue -- dovecot
 /bin/cat /etc/dovecot.conf | \
 /bin/sed -e 's|#default_mail_env =|default_mail_env = mbox:~/mail/:INBOX=mbox|' \
 -e 's|#pop3_uidl_format = %08Xu%08Xv|pop3_uidl_format = %08Xu%08Xv|' \
 > /etc/dovecot.conf.new
 /bin/mv /etc/dovecot.conf.new /etc/dovecot.conf
+%endif
+
+%if "%centos" == "5"
+%triggerin glue -- dovecot
+/bin/cat /etc/dovecot.conf | \
+/bin/sed -e 's|#default_mail_env =|default_mail_env = mbox:~/mail/:INBOX=mbox|' \
+-e 's|#pop3_uidl_format = %08Xu%08Xv|pop3_uidl_format = %08Xu%08Xv|' \
+> /etc/dovecot.conf.new
+/bin/mv /etc/dovecot.conf.new /etc/dovecot.conf
+%endif
+
+%if "%centos" == "6"
+%triggerin glue -- dovecot
+perl -pi -e 's|^#disable_plaintext_auth = (.*)|disable_plaintext_auth = no|g' /etc/dovecot/conf.d/10-auth.conf
+perl -pi -e 's|^#mail_location =(.*)|mail_location = mbox:~/mail/:INBOX=mbox|g' /etc/dovecot/conf.d/10-mail.conf
+%endif
 
 %if "%centos" == "3"
 %triggerin glue -- yum
@@ -367,8 +394,34 @@ fi
 <end $TRIGGERUN>
 
 <begin $CHANGELOG>
-* Thu Jul 21 2011 Michael Stauber <mstauber@solarspeed.net> 2.20110721BX102
+
+* Wed Dec 04 2013 Michael Stauber <mstauber@solarspeed.net> 4.20131204BX109
+- Preparational build for 5207R/5208R. Doesn't include new GUI yet.
+
+* Thu Sep 22 2011 Michael Stauber <mstauber@solarspeed.net> 3.20110922BX108
+- Removed some legacy if-clauses dealing with ancient OS's from templates/rpmdefs.tmpl
+- Change of Apache's 'ServerTokens' moved to relevant constructor of base-apache.mod instead.
+- Modified glue/Makefile to insert 5107R or 5108R model number depending on architecture of the build box.
+
+* Thu Jul 21 2011 Michael Stauber <mstauber@solarspeed.net> 3.20110721BX107
 - Version number bump for the release of the updates backported from 5107R
+
+* Thu Jul 21 2011 Michael Stauber <mstauber@solarspeed.net> 3.20110721BX106
+- Updated triggerin for Dovecot v2.0 handling on CentOS6
+- Post install now also fixes Dovecot v2.0 configs
+
+* Wed Jul 13 2011 Michael Stauber <mstauber@solarspeed.net> 3.20110713BX105
+- templates/rpmdefs.tmpl updated to set shot_open_tag = On in /etc/php.ini
+- Updated version info in glue/Makefile and added support for RHEL6 as well.
+
+* Sat Jun 25 2011 Michael Stauber <mstauber@solarspeed.net> 3.20110625BX104
+- Small buxfix in glue/Makefile to better catch OS version number on SL
+
+* Sat Jun 25 2011 Michael Stauber <mstauber@solarspeed.net> 3.20110625BX103
+- Update to glue/Makefile to better catch OS version number on SL
+
+* Sat Jun 25 2011 Michael Stauber <mstauber@solarspeed.net> 3.20110625BX102
+- Updated build for 5107R
 
 * Wed Jun 15 2011 Michael Stauber <mstauber@solarspeed.net> 2.20110615BX101
 - Removed alias removal from sendmail trigger in templates/rpmdefs.tmpl again. Not needed there as scripts/initSendmail.sh will take care of it anyway.
