0.99.2-1BX08 - Small change in server/cced.init for a proper response on 'reload'.

diff --git a/BlueOnyx/5209R/utils/cce/server/cced.init b/BlueOnyx/5209R/utils/cce/server/cced.init
--- a/BlueOnyx/5209R/utils/cce/server/cced.init
+++ b/BlueOnyx/5209R/utils/cce/server/cced.init
@@ -1,15 +1,8 @@
 #!/bin/sh
-# $Id: cced.init Tue 06 Mar 2012 11:37:12 AM EST mstauber $
-# Copyright 2001 Sun Microsystems, Inc. All rights reserved.
-# Copyright 2012 Team BlueOnyx. All rights reserved.
+# $Id: cced.init
 #
 # cced          This shell script takes care of starting and stopping
 #               cced (configuration engine daemon).
-#
-# chkconfig: 2345 15 97
-# description: cced is the core of sausalito
-# processname: cced
-# config: 
 
 # Source function library.
 . /etc/rc.d/init.d/functions
@@ -90,6 +83,12 @@ case "$1" in
   reload)
 	echo -n "Reloading cced configuration: "
 	killall -HUP cced >/dev/null 2>&1
+	RETVAL=$?
+	if [ $RETVAL -eq 0 ];then
+		echo -n "[ ${green}OK${reset} ]"
+	else 
+		echo -n "[ ${red}FAIL${reset} ]"
+	fi
 	echo ""
 	;;
   rehash)
@@ -110,3 +109,39 @@ case "$1" in
 esac
 
 exit $RETVAL
+
+# 
+# Copyright (c) 2016 Michael Stauber, SOLARSPEED.NET
+# Copyright (c) 2016 Team BlueOnyx, BLUEONYX.IT
+# Copyright (c) 2003 Sun Microsystems, Inc. 
+# All Rights Reserved.
+# 
+# 1. Redistributions of source code must retain the above copyright 
+#	 notice, this list of conditions and the following disclaimer.
+# 
+# 2. Redistributions in binary form must reproduce the above copyright 
+#	 notice, this list of conditions and the following disclaimer in 
+#	 the documentation and/or other materials provided with the 
+#	 distribution.
+# 
+# 3. Neither the name of the copyright holder nor the names of its 
+#	 contributors may be used to endorse or promote products derived 
+#	 from this software without specific prior written permission.
+# 
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
+# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
+# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
+# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
+# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
+# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
+# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
+# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
+# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
+# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
+# POSSIBILITY OF SUCH DAMAGE.
+# 
+# You acknowledge that this software is not designed or intended for 
+# use in the design, construction, operation or maintenance of any 
+# nuclear facility.
+# 
